version: '3.9'

services:
  frontend:
    build:
      context: ./securewebsite.client
    container_name: frontend
    ports:
      - "80:80"  # Nginx expone el puerto 80
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./SecureWebSite.Server
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDatabase;User Id=sa;Password=YourStrongPassword!123;
    expose:
      - "7239:7239"
      - "5003:5003"  # Puerto interno para el contenedor
    networks:
      - app_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!123
    ports:
      - "1433:1433"  # Puerto de SQL Server
    networks:
      - app_network
    volumes:
      - sqlserver_data:/var/opt/mssql

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"  # Nginx expone el puerto 80
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

volumes:
  sqlserver_data:

networks:
  app_network:
    driver: bridge